name: Build firmware on manual trigger

on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Setup Git credentials
            run: |
              git config --global credential.helper store
              echo https://${{ secrets.CICD_KEY }}:x-oauth-basic@github.com > ~/.git-credentials
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - uses: actions/setup-python@v4
            with:
              python-version: '3.11'
    
          - name: Install PlatformIO Core
            run: pip install --upgrade platformio

          - name: Build PlatformIO Project
            run: pio run
             
            