# Workflow for PlatformIO Project
name: ESP-cpp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: pip install -U platformio

      # Working but fails to find wifi.h?
      - name: Build PlatformIO Project
        run: pio ci -c platformio.ini
